const noop = () => {};
export const a = noop;
export const b = noop;
export const c = noop;
export const d = noop;
export const e = noop;
export const i = noop;
export const o = noop;
export const p = noop;
export const s = noop;
export const x = noop;